// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:afterlife_projects/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxvr39-ovHPSTCp1C-jEfhvd4pcRFG74',
    appId: '1:79023947203:web:2f9feb368cfd9263c09176',
    messagingSenderId: '79023947203',
    projectId: 'afterlife-project-d912e',
    authDomain: 'afterlife-project-d912e.firebaseapp.com',
    storageBucket: 'afterlife-project-d912e.firebasestorage.app',
    measurementId: 'G-YNCJDR9YGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgj4tcc4JJo_mdd_-IDQhD7QxgP7MIHuY',
    appId: '1:79023947203:android:7aa9b4cd898d61a3c09176',
    messagingSenderId: '79023947203',
    projectId: 'afterlife-project-d912e',
    storageBucket: 'afterlife-project-d912e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlt9B5mWl_C2GvezEfzxWd-JQDx9mLgiw',
    appId: '1:79023947203:ios:e196443b6f2ad071c09176',
    messagingSenderId: '79023947203',
    projectId: 'afterlife-project-d912e',
    storageBucket: 'afterlife-project-d912e.firebasestorage.app',
    iosBundleId: 'com.example.afterlifeProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlt9B5mWl_C2GvezEfzxWd-JQDx9mLgiw',
    appId: '1:79023947203:ios:e196443b6f2ad071c09176',
    messagingSenderId: '79023947203',
    projectId: 'afterlife-project-d912e',
    storageBucket: 'afterlife-project-d912e.firebasestorage.app',
    iosBundleId: 'com.example.afterlifeProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKxvr39-ovHPSTCp1C-jEfhvd4pcRFG74',
    appId: '1:79023947203:web:adcc54808cebb659c09176',
    messagingSenderId: '79023947203',
    projectId: 'afterlife-project-d912e',
    authDomain: 'afterlife-project-d912e.firebaseapp.com',
    storageBucket: 'afterlife-project-d912e.firebasestorage.app',
    measurementId: 'G-9WZY5XHWKV',
  );
}
